In [19]:
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt

from IPython.display import Image

# enables inline plots, without it plots don't show up in the notebook
%matplotlib inline

In [72]:
df = pd.read_csv('data/subway_tract_intersect_0.csv')
df1 = pd.read_csv('data/turnstile_160507 copy.txt')

In [73]:
capitalizer = lambda x: x.upper()
df['name'] = df['name'].apply(capitalizer)

clean_ave = lambda x: re.sub('AVE','AV', x)
df['name'] = df['name'].apply(clean_ave)

In [77]:
# def clean_numbers(x):
#     matches = re.search(r'([\b\d+])([RD])', x)
#     for match in matches:
#         match.group(2) = ''

clean_numbers1 = lambda x: re.sub(r'(\b\d+)(RD\b)',r'\1', x)
df['name'] = df['name'].apply(clean_numbers1)

clean_numbers2 = lambda x: re.sub(r'(\b\d+)(TH\b)',r'\1', x)
df['name'] = df['name'].apply(clean_numbers2)

clean_numbers3 = lambda x: re.sub(r'(\b\d+)(ST\b)',r'\1', x)
df['name'] = df['name'].apply(clean_numbers3)

clean_numbers4 = lambda x: re.sub(r'(\b\d+)(ND\b)',r'\1', x)
df['name'] = df['name'].apply(clean_numbers4)

clean_dashes = lambda x: re.sub(r'(\w*)(\s-\s)(\w*)',r'\1-\3', x)
df['name'] = df['name'].apply(clean_dashes)

df.sample(40)

,OBJECTID_1,Join_Count,TARGET_FID,notes,url,name,objectid,line,STATEFP,COUNTYFP,...,GISJOIN_1,STATEA,COUNTY,COUNTYA,TRACTA,NAME_1,LGH001,GISJOIN_Text,x,y
138,139,1,195,"1-all times, 2-nights",http://web.mta.info/nyct/service/,CHRISTOPHER ST-SHERIDAN SQ,195.0,1-2,36,61,...,G3600610007300,36.0,New York County,61.0,7300.0,Census Tract 73,6215.0,G3600610007300,-74.002908,40.733425
55,56,1,80,"N,Q-all times, R-all times exc nights, W part ...",http://web.mta.info/nyct/service/,TIMES SQ-42 ST,80.0,N-Q-R-W,36,61,...,G3600610011300,36.0,New York County,61.0,11300.0,Census Tract 113,117.0,G3600610011300,-73.986765,40.754611
60,61,1,85,"4 nights, 6-all times, 6 Express-weekdays AM s...",http://web.mta.info/nyct/service/,51 ST,85.0,4-6-6 Express,36,61,...,G3600610010000,36.0,New York County,61.0,10000.0,Census Tract 100,1992.0,G3600610010000,-73.971916,40.757109
183,184,1,246,F-all times,http://web.mta.info/nyct/service/,SUTPHIN BLVD,246.0,F,36,81,...,G3600810023800,36.0,Queens County,81.0,23800.0,Census Tract 238,5101.0,G3600810023800,-73.810830,40.705421
102,103,1,143,"E-all times, M-weekdays and evenings",http://web.mta.info/nyct/service/,LEXINGTON AV-53 ST,143.0,E-M,36,61,...,G3600610009800,36.0,New York County,61.0,9800.0,Census Tract 98,7316.0,G3600610009800,-73.969068,40.757469
167,168,1,230,7-all times,http://web.mta.info/nyct/service/,69 ST,230.0,7,36,81,...,G3600810026300,36.0,Queens County,81.0,26300.0,Census Tract 263,6220.0,G3600810026300,-73.896403,40.746323
317,318,1,465,"A-all times, S Euclid Av to Ozone Park-Leffert...",http://web.mta.info/nyct/service/,80 ST,465.0,A-S,36,81,...,G3600810004401,36.0,Queens County,81.0,4401.0,Census Tract 44.01,3500.0,G3600810004401,-73.858989,40.679368
322,323,1,471,Q-all times,http://web.mta.info/nyct/service/,72 ST,641.0,Q,36,61,...,G3600610012600,36.0,New York County,61.0,12600.0,Census Tract 126,12774.0,G3600610012600,-73.958360,40.768805
227,228,1,359,"1,2,3-all times",http://web.mta.info/nyct/service/,TIMES SQ-42 ST,359.0,1-2-3,36,61,...,G3600610011300,36.0,New York County,61.0,11300.0,Census Tract 113,117.0,G3600610011300,-73.987493,40.755292
188,189,1,253,"2-all times, 5-all times exc nights, skips rus...",http://web.mta.info/nyct/service/,JACKSON AV,253.0,2-5,36,5,...,G3600050007900,36.0,Bronx County,5.0,7900.0,Census Tract 79,6733.0,G3600050007900,-73.907704,40.816439
158,159,1,221,"4-nights, 3-all other times",http://web.mta.info/nyct/service/,SARATOGA AV,221.0,3-4,36,47,...,G3600470089800,36.0,Kings County,47.0,89800.0,Census Tract 898,2089.0,G3600470089800,-73.916328,40.661531
159,160,1,222,"4-nights, 3-all other times",http://web.mta.info/nyct/service/,SUTTER AV-RUTLAND ROAD,222.0,3-4,36,47,...,G3600470090000,36.0,Kings County,47.0,90000.0,Census Tract 900,5508.0,G3600470090000,-73.922517,40.664768
116,117,1,159,1-all times,http://web.mta.info/nyct/service/,103 ST,159.0,1,36,61,...,G3600610019100,36.0,New York County,61.0,19100.0,Census Tract 191,8807.0,G3600610019100,-73.968376,40.799447
70,71,1,97,"1-all times, 2-nights",http://web.mta.info/nyct/service/,HOUSTON ST,97.0,1-2,36,61,...,G3600610003700,36.0,New York County,61.0,3700.0,Census Tract 37,2447.0,G3600610003700,-74.005369,40.728251
17,18,1,25,"7-all times, 7 Express-rush hours AM westbound...",http://web.mta.info/nyct/service/,FLUSHING-MAIN ST,25.0,7-7 Express,36,81,...,G3600810085300,36.0,Queens County,81.0,85300.0,Census Tract 853,5764.0,G3600810085300,-73.830027,40.759599
277,278,1,421,"N-nights, R-all other times",http://web.mta.info/nyct/service/,WHITEHALL ST,421.0,R-W,36,61,...,G3600610000900,36.0,New York County,61.0,900.0,Census Tract 9,731.0,G3600610000900,-74.013005,40.703140
80,81,1,115,"4-nights, 3-all other times, 2-all times",http://web.mta.info/nyct/service/,GRAND ARMY PLAZA,115.0,2-3-4,36,47,...,G3600470015900,36.0,Kings County,47.0,15900.0,Census Tract 159,5036.0,G3600470015900,-73.970955,40.675294
37,38,1,57,"A-nights, B-weekdays and evenings, C-all times...",http://web.mta.info/nyct/service/,96 ST,57.0,A-B-C,36,61,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,-73.964604,40.791619
198,199,1,288,S to Prospect Park-all times,http://web.mta.info/nyct/service/,FRANKLIN AV-FULTON ST,288.0,S,36,47,...,G3600470022700,36.0,Kings County,47.0,22700.0,Census Tract 227,3454.0,G3600470022700,-73.955827,40.680595
184,185,1,247,"E,J-all times, Z-rush hours AM westbound, PM e...",http://web.mta.info/nyct/service/,JAMAICA CTR-PARSONS / ARCHER,247.0,E-J-Z,36,81,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,-73.801092,40.702064
50,51,1,74,L-all times,http://web.mta.info/nyct/service/,WILSON AV,74.0,L,36,47,...,G3600470040900,36.0,Kings County,47.0,40900.0,Census Tract 409,3752.0,G3600470040900,-73.903958,40.688864
100,101,1,141,"4-all times, skips rush hours AM southbound, P...",http://web.mta.info/nyct/service/,138 ST-GRAND CONCOURSE,141.0,4-5,36,5,...,G3600050005100,36.0,Bronx County,5.0,5100.0,Census Tract 51,5810.0,G3600050005100,-73.929848,40.813223
82,83,1,117,"A-nights, C-all other times",http://web.mta.info/nyct/service/,ROCKAWAY AV,117.0,A-C,36,47,...,G3600470030100,36.0,Kings County,47.0,30100.0,Census Tract 301,2750.0,G3600470030100,-73.911944,40.678340
59,60,1,84,"B,M-weekdays and evenings, D,F-all times",http://web.mta.info/nyct/service/,W 4 ST-WASHINGTON SQ (LOWER),84.0,B-D-F-M,36,61,...,G3600610006500,36.0,New York County,61.0,6500.0,Census Tract 65,6202.0,G3600610006500,-74.000312,40.732254
252,253,1,384,L-all times,http://web.mta.info/nyct/service/,UNION SQ-14 ST,384.0,L,36,61,...,G3600610006100,36.0,New York County,61.0,6100.0,Census Tract 61,5224.0,G3600610006100,-73.990673,40.734765
161,162,1,224,"J-all times, Z-rush hours AM westbound, PM eas...",http://web.mta.info/nyct/service/,BROADWAY JUNCTION,224.0,J-Z,36,47,...,G3600470040500,36.0,Kings County,47.0,40500.0,Census Tract 405,1480.0,G3600470040500,-73.904291,40.679368
90,91,1,127,"A-all times, C-all times exc nights",http://web.mta.info/nyct/service/,NOSTRAND AV,127.0,A-C,36,47,...,G3600470024700,36.0,Kings County,47.0,24700.0,Census Tract 247,2316.0,G3600470024700,-73.950428,40.680438
246,247,1,378,"N-nights, R-all other times",http://web.mta.info/nyct/service/,COURT ST,378.0,N-R,36,47,...,G3600470000900,36.0,Kings County,47.0,900.0,Census Tract 9,4172.0,G3600470000900,-73.991822,40.694198
46,47,1,70,G-all times,http://web.mta.info/nyct/service/,CLASSON AV,70.0,G,36,47,...,G3600470023300,36.0,Kings County,47.0,23300.0,Census Tract 233,5061.0,G3600470023300,-73.959986,40.688892
25,26,1,36,"D,N-nights, R-all other times",http://web.mta.info/nyct/service/,UNION ST,36.0,D-N-R,36,47,...,G3600470013300,36.0,Kings County,47.0,13300.0,Census Tract 133,3730.0,G3600470013300,-73.983109,40.677318
117,118,1,160,"2,3-all times",http://web.mta.info/nyct/service/,CENTRAL PARK NORTH (110 ST),160.0,2-3,36,61,...,G3600610018600,36.0,New York County,61.0,18600.0,Census Tract 186,5701.0,G3600610018600,-73.951820,40.799073
234,235,1,366,"B,M-weekdays and evenings, D,F-all times",http://web.mta.info/nyct/service/,HERALD SQ-34 ST,366.0,B-D-F-M,36,61,...,G3600610007600,36.0,New York County,61.0,7600.0,Census Tract 76,2277.0,G3600610007600,-73.987771,40.749787
290,291,1,435,"N-all times, Q-weekdays and evenings",http://web.mta.info/nyct/service/,CANAL ST,435.0,N-Q,36,61,...,G3600610004500,36.0,New York County,61.0,4500.0,Census Tract 45,1136.0,G3600610004500,-74.001057,40.718815
85,86,1,120,"B-weekdays and evenings, Q-all times",http://web.mta.info/nyct/service/,7 AV,120.0,B-Q,36,47,...,G3600470016100,36.0,Kings County,47.0,16100.0,Census Tract 161,3075.0,G3600470016100,-73.972850,40.677100
157,158,1,218,"4-nights, 3-all other times",http://web.mta.info/nyct/service/,ROCKAWAY AV,218.0,3-4,36,47,...,G3600470092400,36.0,Kings County,47.0,92400.0,Census Tract 924,2656.0,G3600470092400,-73.908962,40.662614
191,192,1,258,6-all times,http://web.mta.info/nyct/service/,E 143 ST-ST MARY'S ST,258.0,6,36,5,...,G3600050003100,36.0,Bronx County,5.0,3100.0,Census Tract 31,1597.0,G3600050003100,-73.907659,40.808722
135,136,1,192,"A-all times, S Euclid Av to Ozone Park-Leffert...",http://web.mta.info/nyct/service/,GRANT AV,192.0,A-S,36,47,...,G3600470120200,36.0,Kings County,47.0,120200.0,Census Tract 1202,1900.0,G3600470120200,-73.865052,40.677045
257,258,1,395,"A-nights, C-all other times, E-all times",http://web.mta.info/nyct/service/,SPRING ST,395.0,A-C-E,36,61,...,G3600610004900,36.0,New York County,61.0,4900.0,Census Tract 49,4942.0,G3600610004900,-74.003743,40.726229
229,230,1,361,"A-all times, C-all times exc nights",http://web.mta.info/nyct/service/,CHAMBERS ST,361.0,A-C,36,61,...,G3600610002100,36.0,New York County,61.0,2100.0,Census Tract 21,6040.0,G3600610002100,-74.008585,40.714110
224,225,1,356,"N-all times, R-all times exc nights, W part time",http://web.mta.info/nyct/service/,5 AV-59 ST,356.0,N-R-W,36,61,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,-73.973344,40.764811

In [19]:
df1.head()

,C/A,UNIT,SCP,STATION,LINENAME,DIVISION,DATE,TIME,DESC,ENTRIES,EXITS
0,A002,R051,02-00-00,59 ST,NQR456,BMT,04/30/2016,00:00:00,REGULAR,5639941,1909983
1,A002,R051,02-00-00,59 ST,NQR456,BMT,04/30/2016,04:00:00,REGULAR,5639991,1909993
2,A002,R051,02-00-00,59 ST,NQR456,BMT,04/30/2016,08:00:00,REGULAR,5640014,1910024
3,A002,R051,02-00-00,59 ST,NQR456,BMT,04/30/2016,12:00:00,REGULAR,5640158,1910134
4,A002,R051,02-00-00,59 ST,NQR456,BMT,04/30/2016,16:00:00,REGULAR,5640454,1910197

In [24]:
df1.shape

(194466, 11)

In [80]:
df3 = pd.merge(df, df1, how='inner', left_on='name', right_on='STATION')

In [93]:
set(df1.STATION).difference(set(df.name))

{'103 ST-CORONA',
 '116 ST-COLUMBIA',
 '137 ST CITY COL',
 '138/GRAND CONC',
 '14 ST-UNION SQ',
 '149/GRAND CONC',
 '14TH STREET',
 '15 ST-PROSPECT',
 '155 ST',
 '157 ST',
 '161/YANKEE STAD',
 '163 ST-AMSTERDM',
 '167 ST',
 '168 ST',
 '170 ST',
 '174 ST',
 '174-175 STS',
 '175 ST',
 '176 ST',
 '18 AV',
 '181 ST',
 '182-183 STS',
 '183 ST',
 '190 ST',
 '191 ST',
 '2 AV',
 '20 AV',
 '207 ST',
 '21 ST-QNSBRIDGE',
 '215 ST',
 '219 ST',
 '225 ST',
 '231 ST',
 '233 ST',
 '238 ST',
 '25 AV',
 '3 AV 138 ST',
 '33 ST-RAWSON ST',
 '34 ST-HERALD SQ',
 '34 ST-HUDSON YD',
 '34 ST-PENN STA',
 '40 ST LOWERY ST',
 '42 ST-PORT AUTH',
 '45 ST',
 '46 ST BLISS ST',
 '47-50 STS ROCK',
 '4AV-9 ST',
 '5 AV/53 ST',
 '5 AV/59 ST',
 '5 AVE',
 '53 ST',
 '55 ST',
 '57 ST-7 AV',
 '59 ST',
 '59 ST COLUMBUS',
 '61 ST WOODSIDE',
 '66 ST-LINCOLN',
 '68ST-HUNTER CO',
 '71 ST',
 '75 ST-ELDERTS',
 '81 ST-MUSEUM',
 '82 ST-JACKSON H',
 '85 ST-FOREST PK',
 '9 AV',
 '90 ST-ELMHURST',
 '9TH STREET',
 'ALLERTON AV',
 'AQUEDUCT N.COND',
 'AQUEDUCT RACETR',
 'ASTORIA DITMARS',
 'ATL AV-BARCLAY',
 'AVENUE H',
 'AVENUE I',
 'AVENUE J',
 'AVENUE M',
 'AVENUE N',
 'AVENUE P',
 'AVENUE U',
 'AVENUE X',
 "B'WAY-LAFAYETTE",
 'BAY 50 ST',
 'BAY PKWY',
 'BAY RIDGE AV',
 'BAYCHESTER AV',
 'BEACH 105 ST',
 'BEACH 25 ST',
 'BEACH 36 ST',
 'BEACH 44 ST',
 'BEACH 60 ST',
 'BEACH 67 ST',
 'BEACH 90 ST',
 'BEACH 98 ST',
 'BEDFORD PK BLVD',
 'BEDFORD-NOSTRAN',
 'BEVERLEY ROAD',
 'BEVERLY RD',
 'BRIARWOOD',
 'BRIGHTON BEACH',
 'BROAD CHANNEL',
 'BROADWAY JCT',
 'BRONX PARK EAST',
 'BROOKLYN BRIDGE',
 'BUHRE AV',
 'BURKE AV',
 'BURNSIDE AV',
 'BUSHWICK AV',
 'CANARSIE-ROCKAW',
 'CASTLE HILL AV',
 'CATHEDRAL PKWY',
 'CENTRAL PK N110',
 'CHRISTOPHER ST',
 'CHURCH AV',
 'CITY / BUS',
 'CLINTON-WASH AV',
 'CONEY IS-STILLW',
 'CORTELYOU RD',
 'CROWN HTS-UTICA',
 'DELANCEY/ESSEX',
 'DITMAS AV',
 'DYCKMAN ST',
 "E 143/ST MARY'S",
 'E 180 ST',
 'EAST 105 ST',
 'EASTCHSTER/DYRE',
 'EASTN PKWY-MUSM',
 'ELDER AV',
 'EXCHANGE PLACE',
 'FAR ROCKAWAY',
 'FLATBUSH AV-B.C',
 'FLUSHING-MAIN',
 'FORDHAM RD',
 'FOREST AVE',
 'FOREST HILLS 71',
 'FREEMAN ST',
 'FT HAMILTON PKY',
 'GRAND ARMY PLAZ',
 'GRAND-NEWTOWN',
 'GRD CNTRL-42 ST',
 'GROVE STREET',
 'GUN HILL RD',
 'HARLEM 148 ST',
 'HARRISON',
 'HOWARD BCH JFK',
 'HOYT-SCHER',
 'HUNTERS PT AV',
 'INWOOD-207 ST',
 'JAMAICA 179 ST',
 'JAMAICA CENTER',
 'JAMAICA VAN WK',
 'JAY ST-METROTEC',
 'JFK JAMAICA CT1',
 'JKSN HT-ROOSVLT',
 'JOURNAL SQUARE',
 'KEW GARDENS',
 'KINGS HWY',
 'KINGSBRIDGE RD',
 'KINGSTON-THROOP',
 'KNICKERBOCKER',
 'LACKAWANNA',
 'LEXINGTON AV/53',
 'LEXINGTON AV/63',
 'MARBLE HILL-225',
 'METS-WILLETS PT',
 'MIDDLETOWN RD',
 'MORISN AV/SNDVW',
 'MORRIS PARK',
 'MOSHOLU PKWY',
 'MT EDEN AV',
 'MYRTLE-WILLOUGH',
 'MYRTLE-WYCKOFF',
 'NASSAU ST',
 'NECK RD',
 'NEPTUNE AV',
 'NEREID AV',
 'NEW LOTS',
 'NEW UTRECHT AV',
 'NEWARK BM BW',
 'NEWARK C',
 'NEWARK HM HE',
 'NEWARK HW BMEBE',
 'NEWKIRK AV',
 'NEWKIRK PLAZA',
 'NORWOOD 205 ST',
 'OCEAN PKWY',
 'ORCHARD BEACH',
 'OZONE PK LEFFRT',
 'PARK PLACE',
 'PARKCHESTER',
 'PARKSIDE AV',
 'PATH WTC',
 'PATH WTC 2',
 'PAVONIA/NEWPORT',
 'PELHAM BAY PARK',
 'PELHAM PKWY',
 'QUEENS PLAZA',
 'RIT-MANHATTAN',
 'RIT-ROOSEVELT',
 'ROCKAWAY PARK B',
 'ROOSEVELT ISLND',
 'SENECA AVE',
 'SHEEPSHEAD BAY',
 'SMITH-9 ST',
 'ST LAWRENCE AV',
 'ST. GEORGE',
 'SUTPHIN-ARCHER',
 'SUTTER AV-RUTLD',
 'THIRTY ST',
 'THIRTY THIRD ST',
 'TOMPKINSVILLE',
 'TREMONT AV',
 'TWENTY THIRD ST',
 'V.CORTLANDT PK',
 'VAN SICLEN AVE',
 'VERNON-JACKSON',
 'W 4 ST-WASH SQ',
 'W 8 ST-AQUARIUM',
 'WAKEFIELD/241',
 'WEST FARMS SQ',
 'WESTCHESTER SQ',
 'WHITEHALL S-FRY',
 'WHITLOCK AV',
 'WOODHAVEN BLVD',
 'WOODLAWN',
 'WORLD TRADE CTR',
 'ZEREGA AV'}

In [67]:
df.name.unique

<bound method Series.unique of 0                       ASTOR PL
1                       CANAL ST
2                          50 ST
3                      BERGEN ST
4                PENNSYLVANIA AV
5        CATHEDRAL PKWY (110 ST)
6            KINGSTON-THROOP AVS
7                          65 ST
8                          36 ST
9           DELANCEY ST-ESSEX ST
10                 VAN SICLEN AV
11                    NORWOOD AV
12                 104-102ND STS
13                     DEKALB AV
14                  INTERVALE AV
15            METS-WILLETS POINT
16                 JUNCTION BLVD
17              FLUSHING-MAIN ST
18                   3 AV-138 ST
19     BROOKLYN BRIDGE-CITY HALL
20         GRAND CENTRAL-42ND ST
21                         33 ST
22                         96 ST
23                         77 ST
24                   CHAUNCEY ST
25                      UNION ST
26                   ELMHURST AV
27                      RALPH AV
28                   FRANKLIN AV
29                    SIMPSON ST
                 ...
295                       135 ST
296                        14 ST
297                         6 AV
298                         8 AV
299                        14 ST
300                  NOSTRAND AV
301                     CLARK ST
302                  FRANKLIN AV
303       CLINTON-WASHINGTON AVS
304                    FOREST AV
305                       110 ST
306                        86 ST
307                      YORK ST
308                      HIGH ST
309                 LAFAYETTE AV
310                 PRESIDENT ST
311                  BLEECKER ST
312                       103 ST
313                    EUCLID AV
314                        88 ST
315                       116 ST
316                  FRANKLIN ST
317                        80 ST
318               5 AV-BRYANT PK
319                    SPRING ST
320                       125 ST
321           34 ST-HUDSON YARDS
322                      72ND ST
323                        86 ST
324                        96 ST
Name: name, dtype: object>

In [76]:
df1.STATION.value_counts()

34 ST-PENN STA     4957
FULTON ST          4102
23 ST              3005
GRD CNTRL-42 ST    2609
CANAL ST           2477
34 ST-HERALD SQ    2331
CHAMBERS ST        2267
86 ST              2204
42 ST-PORT AUTH    2198
TIMES SQ-42 ST     2149
59 ST              2147
WALL ST            2110
ATL AV-BARCLAY     2025
125 ST             1819
14 ST              1804
59 ST COLUMBUS     1721
CHURCH AV          1596
14 ST-UNION SQ     1592
50 ST              1570
161/YANKEE STAD    1562
28 ST              1554
96 ST              1553
47-50 STS ROCK     1541
METS-WILLETS PT    1530
JAY ST-METROTEC    1507
LEXINGTON AV/53    1343
CORTLANDT ST       1311
BOWLING GREEN      1218
BOROUGH HALL       1152
FLUSHING-MAIN      1150
                   ...
CORTELYOU RD        126
25 AV               126
219 ST              126
JUNIUS ST           126
NORWOOD AV          126
KINGSTON AV         126
BAYCHESTER AV       126
PRESIDENT ST        126
BAY 50 ST           126
PARKSIDE AV         126
NEW LOTS            126
BOWERY              126
182-183 STS         126
238 ST              126
HEWES ST            126
CHAUNCEY ST         126
BEVERLEY ROAD       126
BURKE AV            126
GATES AV            126
ALLERTON AV         126
65 ST               126
MORRIS PARK         126
AVENUE X            126
LIBERTY AV          126
KOSCIUSZKO ST       125
138/GRAND CONC      124
YORK ST             124
SUTTER AV            84
CLEVELAND ST         84
PATH WTC 2           40
Name: STATION, dtype: int64

In [15]:
import re
match = re.search(r'\b\d+\w\w', "12RD ST")
str = match.group()
print(str)
new_str = re.sub('RD', '', str)
print(new_str)

12RD
12

In [17]:
name = "3RD AVE"
new_name = re.sub('AVE', 'AV', name)
print(new_name)

3RD AV

In [81]:
df3.info()

<class 'pandas.core.frame.DataFrame'>
Int64Index: 181208 entries, 0 to 181207
Data columns (total 39 columns):
OBJECTID_1                                                              181208 non-null int64
Join_Count                                                              181208 non-null int64
TARGET_FID                                                              181208 non-null int64
notes                                                                   181208 non-null object
url                                                                     181208 non-null object
name                                                                    181208 non-null object
objectid                                                                181208 non-null float64
line                                                                    181208 non-null object
STATEFP                                                                 181208 non-null int64
COUNTYFP                                                                181208 non-null int64
TRACTCE                                                                 181208 non-null int64
AFFGEOID                                                                181208 non-null object
GEOID                                                                   181208 non-null int64
NAME                                                                    181208 non-null float64
LSAD                                                                    181208 non-null object
ALAND                                                                   181208 non-null float64
AWATER                                                                  181208 non-null float64
GISJOIN                                                                 181208 non-null object
GISJOIN_1                                                               172798 non-null object
STATEA                                                                  172798 non-null float64
COUNTY                                                                  172798 non-null object
COUNTYA                                                                 172798 non-null float64
TRACTA                                                                  172798 non-null float64
NAME_1                                                                  172798 non-null object
LGH001                                                                  172798 non-null float64
GISJOIN_Text                                                            172798 non-null object
x                                                                       181208 non-null float64
y                                                                       181208 non-null float64
C/A                                                                     181208 non-null object
UNIT                                                                    181208 non-null object
SCP                                                                     181208 non-null object
STATION                                                                 181208 non-null object
LINENAME                                                                181208 non-null object
DIVISION                                                                181208 non-null object
DATE                                                                    181208 non-null object
TIME                                                                    181208 non-null object
DESC                                                                    181208 non-null object
ENTRIES                                                                 181208 non-null int64
EXITS                                                                   181208 non-null int64
dtypes: float64(10), int64(9), object(20)
memory usage: 55.3+ MB

In [79]:
df1.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 194466 entries, 0 to 194465
Data columns (total 11 columns):
C/A                                                                     194466 non-null object
UNIT                                                                    194466 non-null object
SCP                                                                     194466 non-null object
STATION                                                                 194466 non-null object
LINENAME                                                                194466 non-null object
DIVISION                                                                194466 non-null object
DATE                                                                    194466 non-null object
TIME                                                                    194466 non-null object
DESC                                                                    194466 non-null object
ENTRIES                                                                 194466 non-null int64
EXITS                                                                   194466 non-null int64
dtypes: int64(2), object(9)
memory usage: 16.3+ MB

In [ ]:
print()